### ISSUE TITLE
[REFACTOR] DDD 기반으로 프로젝트 구조를 변경한다.

### ISSUE THREAD

**Issue by younghch** [chin-da/Backend#22]
## ✅ 구현할 기능

- 바운디드 컨텍스 별로 서버를 구분한다.
- core에서 전체 모듈을 빌드하고 공유하는 구조 대신 공유가 필요한 클래스들은 shared-kernel 내에 정의한다.
- Provider클래스를 역할이 분명한 엔티티/클래스로 변경
- 환경 변수에 키값 세팅 및 파싱 기능 구현

## 📝 TODO
- [X] 바운디드 컨텍스 별로 서버를 구분
- [X] shared-kernel 정의 
- [X] Provider클래스를 역할이 분명한 엔티티/클래스로 변경 
- [X] 환경 변수에 키값 세팅 및 파싱 기능 구현
